import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme-provider";
import { getHeader } from "@/lib/queries";
import "aos/dist/aos.css";
import type { Metadata } from "next";
import { DM_Sans, Lexend } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = await getHeader();
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${lexend.variable} antialiased font-sans`}
      >
        <ThemeProvider
          defaultTheme="system"
          attribute={"class"}
          storageKey="theme"
          enableSystem
          enableColorScheme
        >
          <Suspense fallback="loading">
            <Header data={header} />
          </Suspense>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
